# Copyright (C) 2022-Present Indoc Systems
#
# Licensed under the GNU AFFERO GENERAL PUBLIC LICENSE,
# Version 3.0 (the "License") available at https://www.gnu.org/licenses/agpl-3.0.en.html.
# You may not use this file except in compliance with the License.
"""Adding a column to metadata.

Revision ID: 0003
Revises: 0002
Create Date: 2024-08-11 13:11:25.776275
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'metadata',
        sa.Column('direction', sa.VARCHAR(3), nullable=False, server_default='KG'),
        schema='kg_integration',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metadata', 'direction', schema='kg_integration')
    # ### end Alembic commands ###
